import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import * as schema from "../lib/db/src/schema/index";
import { sql } from "drizzle-orm";

const connectionString = "postgresql://postgres.ysenimczeasmaeojzlkt:GewbDhrbzw0vdrtj@aws-1-ap-south-1.pooler.supabase.com:6543/postgres";
const pool = new Pool({ connectionString });
const db = drizzle(pool, { schema });

const resources = [
  {
    title: "Emotional Intelligence at Work",
    provider: "Coursera (UC Davis)",
    url: "https://www.coursera.org/learn/emotional-intelligence-at-work",
    language: "en",
    languageLabel: "English",
    isFree: "audit",
    level: "beginner",
    durationHours: 12,
    targetDimension: "D6", 
    riskLevelTarget: "critical",
    tags: ["Leadership", "Empathy", "Soft Skills"],
    rating: 4.8,
    reviewCount: 45000,
  },
  {
    title: "Negotiation, Mediation, and Conflict Resolution",
    provider: "ESSEC Business School",
    url: "https://www.coursera.org/specializations/negotiation-mediation",
    language: "en",
    languageLabel: "English",
    isFree: "audit",
    level: "advanced",
    durationHours: 40,
    targetDimension: "D3",
    riskLevelTarget: "high",
    tags: ["Negotiation", "Conflict Resolution", "Strategy"],
    rating: 4.9,
    reviewCount: 32000,
  },
  {
    title: "Creative Problem Solving",
    provider: "University of Minnesota",
    url: "https://www.coursera.org/learn/creative-problem-solving",
    language: "en",
    languageLabel: "English",
    isFree: "audit",
    level: "beginner",
    durationHours: 14,
    targetDimension: "general",
    riskLevelTarget: "all",
    tags: ["Innovation", "Critical Thinking", "Creativity"],
    rating: 4.8,
    reviewCount: 21000,
  },
  {
    title: "Inteligencia Emocional y Liderazgo",
    provider: "Tecnológico de Monterrey",
    url: "https://www.coursera.org/learn/inteligencia-emocional",
    language: "es",
    languageLabel: "Español",
    isFree: "audit",
    level: "intermediate",
    durationHours: 15,
    targetDimension: "D6",
    riskLevelTarget: "moderate",
    tags: ["Liderazgo", "Inteligencia Emocional", "ES"],
    rating: 4.7,
    reviewCount: 15000,
  },
  {
    title: "Strategic Leadership and Management",
    provider: "University of Illinois",
    url: "https://www.coursera.org/specializations/strategic-leadership",
    language: "en",
    languageLabel: "English",
    isFree: "scholarship",
    level: "advanced",
    durationHours: 60,
    targetDimension: "D3",
    riskLevelTarget: "critical",
    tags: ["Management", "Strategy", "Leadership"],
    rating: 4.9,
    reviewCount: 52000,
  },
  {
    title: "La Résolution de Problèmes Complexes",
    provider: "HEC Paris",
    url: "https://www.coursera.org/learn/resolution-problemes",
    language: "fr",
    languageLabel: "Français",
    isFree: "audit",
    level: "advanced",
    durationHours: 20,
    targetDimension: "D1",
    riskLevelTarget: "high",
    tags: ["Stratégie", "Résolution", "FR"],
    rating: 4.6,
    reviewCount: 8000,
  },
  {
    title: "Design Thinking for Innovation",
    provider: "University of Virginia",
    url: "https://www.coursera.org/learn/uva-darden-design-thinking-innovation",
    language: "en",
    languageLabel: "English",
    isFree: "yes",
    level: "intermediate",
    durationHours: 10,
    targetDimension: "D2",
    riskLevelTarget: "high",
    tags: ["Design Thinking", "Innovation", "Product"],
    rating: 4.8,
    reviewCount: 65000,
  },
  {
    title: "Teamwork Skills: Communicating Effectively",
    provider: "University of Colorado Boulder",
    url: "https://www.coursera.org/learn/teamwork-skills-effective-communication",
    language: "en",
    languageLabel: "English",
    isFree: "audit",
    level: "beginner",
    durationHours: 11,
    targetDimension: "general",
    riskLevelTarget: "all",
    tags: ["Communication", "Teamwork", "Management"],
    rating: 4.7,
    reviewCount: 38000,
  },
  {
    title: "Inspiring and Motivating Individuals",
    provider: "University of Michigan",
    url: "https://www.coursera.org/learn/motivate-people",
    language: "en",
    languageLabel: "English",
    isFree: "audit",
    level: "intermediate",
    durationHours: 14,
    targetDimension: "D6",
    riskLevelTarget: "moderate",
    tags: ["Motivation", "Leadership", "Psychology"],
    rating: 4.9,
    reviewCount: 42000,
  },
  {
    title: "Ethics in Action",
    provider: "Harvard University",
    url: "https://online-learning.harvard.edu/course/ethics-action",
    language: "en",
    languageLabel: "English",
    isFree: "scholarship",
    level: "advanced",
    durationHours: 35,
    targetDimension: "general",
    riskLevelTarget: "critical",
    tags: ["Ethics", "Philosophy", "Decision Making"],
    rating: 4.8,
    reviewCount: 18000,
  },
  {
    title: "Liderazgo Efectivo para el Siglo XXI",
    provider: "Universidad de los Andes",
    url: "https://www.coursera.org/learn/liderazgo",
    language: "es",
    languageLabel: "Español",
    isFree: "audit",
    level: "beginner",
    durationHours: 12,
    targetDimension: "general",
    riskLevelTarget: "all",
    tags: ["Liderazgo", "Management", "ES"],
    rating: 4.8,
    reviewCount: 11000,
  },
  {
    title: "Psychological First Aid",
    provider: "Johns Hopkins University",
    url: "https://www.coursera.org/learn/psychological-first-aid",
    language: "en",
    languageLabel: "English",
    isFree: "yes",
    level: "beginner",
    durationHours: 6,
    targetDimension: "D6",
    riskLevelTarget: "high",
    tags: ["Psychology", "Empathy", "Crisis Management"],
    rating: 4.9,
    reviewCount: 125000,
  },
  {
    title: "Game Theory for Strategic Advantage",
    provider: "MIT OpenCourseWare",
    url: "https://ocw.mit.edu/courses/15-025-game-theory-for-strategic-advantage/",
    language: "en",
    languageLabel: "English",
    isFree: "yes",
    level: "advanced",
    durationHours: 45,
    targetDimension: "D3",
    riskLevelTarget: "critical",
    tags: ["Game Theory", "Strategy", "Economics"],
    rating: 4.9,
    reviewCount: 5000,
  },
  {
    title: "The Science of Well-Being",
    provider: "Yale University",
    url: "https://www.coursera.org/learn/the-science-of-well-being",
    language: "en",
    languageLabel: "English",
    isFree: "audit",
    level: "beginner",
    durationHours: 19,
    targetDimension: "general",
    riskLevelTarget: "all",
    tags: ["Well-being", "Psychology", "Personal Growth"],
    rating: 4.9,
    reviewCount: 400000,
  },
  {
    title: "Agile Leadership Principles",
    provider: "University of Maryland",
    url: "https://www.edx.org/course/agile-leadership-principles",
    language: "en",
    languageLabel: "English",
    isFree: "audit",
    level: "intermediate",
    durationHours: 25,
    targetDimension: "D2",
    riskLevelTarget: "moderate",
    tags: ["Agile", "Leadership", "Management"],
    rating: 4.8,
    reviewCount: 22000,
  },
  {
    title: "Cross-Cultural Communication",
    provider: "FutureLearn",
    url: "https://www.futurelearn.com/courses/cross-cultural-communication",
    language: "en",
    languageLabel: "English",
    isFree: "yes",
    level: "intermediate",
    durationHours: 12,
    targetDimension: "D6",
    riskLevelTarget: "high",
    tags: ["Culture", "Communication", "Diversity"],
    rating: 4.7,
    reviewCount: 14000,
  },
  {
    title: "Mastering Storytelling",
    provider: "Pixar in a Box (Khan Academy)",
    url: "https://www.khanacademy.org/computing/pixar/storytelling",
    language: "en",
    languageLabel: "English",
    isFree: "yes",
    level: "beginner",
    durationHours: 15,
    targetDimension: "D1",
    riskLevelTarget: "moderate",
    tags: ["Storytelling", "Creativity", "Writing"],
    rating: 4.9,
    reviewCount: 88000,
  },
  {
    title: "Complex Systems and Chaos",
    provider: "Santa Fe Institute",
    url: "https://www.complexityexplorer.org/courses",
    language: "en",
    languageLabel: "English",
    isFree: "yes",
    level: "advanced",
    durationHours: 30,
    targetDimension: "D3",
    riskLevelTarget: "critical",
    tags: ["Complexity", "Systems Thinking", "Abstract Logic"],
    rating: 4.8,
    reviewCount: 9500,
  }
];

async function seed() {
  try {
    console.log("Truncating learning paths and resources...");
    // Since pathResources and userPathEnrollments references learningPaths and freeResources via cascade,
    // deleting from learningPaths and freeResources is sufficient.
    await db.execute(sql`TRUNCATE TABLE learning_paths CASCADE;`);
    await db.execute(sql`TRUNCATE TABLE free_resources CASCADE;`);
    
    console.log("Seeding Human-Proof learning resources...");
    for (const r of resources) {
      await db.insert(schema.freeResources).values(r);
    }
    console.log(`✅ Successfully seeded ${resources.length} human-proof resources.`);
    process.exit(0);
  } catch (e) {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  } finally {
    pool.end();
  }
}

seed();
