-- ── SAFE CAREERS TABLE ──
-- AI-resistant careers with verified protection from automation

-- Drop and recreate with expanded schema
DROP TABLE IF EXISTS public.safe_careers CASCADE;

CREATE TABLE IF NOT EXISTS public.safe_careers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    role_title TEXT NOT NULL,
    industry_label TEXT NOT NULL,
    risk_score INTEGER NOT NULL CHECK (risk_score >= 0 AND risk_score <= 100),
    median_salary_usd INTEGER,
    growth_projection INTEGER,
    safety_reason TEXT,
    skills TEXT[],
    confidence_score INTEGER DEFAULT 85,
    last_verified DATE DEFAULT CURRENT_DATE,
    -- Expanded fields for detailed view
    description TEXT,
    entry_requirements TEXT,
    growth_trajectory TEXT,
    key_strengths TEXT[],
    ai_impact_detail TEXT,
    salary_range_low INTEGER,
    salary_range_high INTEGER,
    job_outlook TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.safe_careers ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Public read access for safe_careers" 
ON public.safe_careers FOR SELECT 
USING (true);

-- Index for fast queries
CREATE INDEX IF NOT EXISTS idx_safe_careers_risk ON public.safe_careers(risk_score);
CREATE INDEX IF NOT EXISTS idx_safe_careers_industry ON public.safe_careers(industry_label);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION update_safe_careers_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_safe_careers_modtime
    BEFORE UPDATE ON public.safe_careers
    FOR EACH ROW
    EXECUTE PROCEDURE update_safe_careers_timestamp();

-- ── SEED SAFE CAREERS DATA ──
INSERT INTO public.safe_careers (role_title, industry_label, risk_score, median_salary_usd, growth_projection, safety_reason, skills, confidence_score) VALUES
('Cybersecurity Analyst', 'Technology', 8, 112000, 32, 'Zero-sum offense/defense game; AI cannot anticipate novel attack vectors', ARRAY['Threat Hunting', 'Incident Response', 'Security Architecture'], 95),
('Registered Nurse', 'Healthcare', 5, 82600, 6, 'Hands-on patient care requires human touch and real-time clinical judgment', ARRAY['Patient Assessment', 'Clinical Decision Making', 'Care Coordination'], 98),
('Mental Health Counselor', 'Healthcare', 3, 52400, 15, 'Deep emotional intelligence and therapeutic rapport cannot be replicated', ARRAY['Therapeutic Techniques', 'Crisis Intervention', 'Empathy'], 97),
('Special Education Teacher', 'Education', 6, 64000, 4, 'Individualized accommodation and behavioral intervention require human judgment', ARRAY['IEP Development', 'Behavioral Support', 'Parent Coaching'], 96),
('Physical Therapist', 'Healthcare', 7, 97000, 17, 'Manual therapy and movement assessment require physical embodiment', ARRAY['Manual Therapy', 'Movement Analysis', 'Rehabilitation'], 94),
('AI Ethics Officer', 'Technology', 15, 145000, 45, 'Governance and bias auditing require human accountability', ARRAY['AI Governance', 'Bias Auditing', 'Regulatory Compliance'], 90),
('Healthcare Administrator', 'Healthcare', 22, 104000, 12, 'Complex regulatory navigation requires human judgment', ARRAY['Healthcare Regulation', 'Operations Management'], 88),
('Social Worker', 'Healthcare', 18, 58000, 9, 'Case management and advocacy require deep human empathy', ARRAY['Case Management', 'Advocacy', 'Crisis Intervention'], 92),
('Construction Project Manager', 'Construction', 25, 98000, 8, 'Stakeholder coordination and site safety require human oversight', ARRAY['Project Planning', 'Site Safety', 'Budget Management'], 85),
('Electrician', 'Trades', 12, 61000, 6, 'Installation and troubleshooting require physical presence', ARRAY['Electrical Installation', 'Troubleshooting', 'Code Compliance'], 93),
('Plumber', 'Trades', 11, 64000, 5, 'Pipe fitting and diagnostic problem-solving require manual dexterity', ARRAY['Pipe Fitting', 'Diagnostic Skills', 'Building Codes'], 91),
('HVAC Technician', 'Trades', 14, 56000, 4, 'System installation and troubleshooting require physical presence', ARRAY['System Installation', 'Refrigeration', 'Diagnostics'], 90),
('Pilot', 'Transportation', 18, 160000, 5, 'Aircraft command and emergency response require human decision-making', ARRAY['Flight Operations', 'Emergency Response', 'Navigation'], 95),
('Data Scientist', 'Technology', 45, 130000, 36, 'Model interpretation and business insight require human context', ARRAY['Statistical Analysis', 'ML Modeling', 'Business Intelligence'], 75),
('Marketing Director', 'Marketing', 38, 135000, 10, 'Brand strategy and creative direction require human intuition', ARRAY['Brand Strategy', 'Creative Leadership', 'Campaign Optimization'], 80),
('Financial Advisor', 'Finance', 35, 95000, 7, 'Wealth planning and behavioral coaching require fiduciary trust', ARRAY['Wealth Planning', 'Risk Assessment', 'Client Relationships'], 82),
('Product Manager', 'Technology', 42, 140000, 20, 'Strategic roadmap and stakeholder negotiation require human synthesis', ARRAY['Product Strategy', 'User Research', 'Stakeholder Management'], 78),
('UX Researcher', 'Technology', 40, 105000, 25, 'Qualitative insights and ethnographic research require human connection', ARRAY['User Interviews', 'Usability Testing', 'Journey Mapping'], 83),
('HR Business Partner', 'People Ops', 32, 85000, 8, 'Employee relations and conflict resolution require emotional intelligence', ARRAY['Employee Relations', 'Conflict Resolution', 'Org Development'], 85),
('Sales Director', 'Sales', 48, 145000, 12, 'Complex negotiation and relationship building require human persuasion', ARRAY['Strategic Selling', 'Negotiation', 'Account Management'], 72),
('Attorney', 'Legal', 28, 145000, 4, 'Courtroom advocacy and strategy require human judgment', ARRAY['Legal Strategy', 'Litigation', 'Client Counseling'], 88),
('Prompt Engineer', 'Technology', 55, 125000, 80, 'LLM optimization requires human creativity', ARRAY['Prompt Design', 'LLM Optimization', 'AI Tooling'], 70),
('Machine Learning Operations Engineer', 'Technology', 48, 145000, 45, 'ML pipeline orchestration requires operational expertise', ARRAY['MLOps', 'Pipeline Orchestration', 'Model Monitoring'], 76),
('Cloud Solutions Architect', 'Technology', 42, 155000, 25, 'Complex system design requires architectural judgment', ARRAY['System Architecture', 'Cloud Strategy', 'Security Design'], 80)
ON CONFLICT (role_title, industry_label) DO NOTHING;

-- ── EXPANDED SEED DATA: 52 SAFE CAREERS ──
INSERT INTO public.safe_careers (role_title, industry_label, risk_score, median_salary_usd, growth_projection, safety_reason, skills, confidence_score, description, entry_requirements, growth_trajectory, key_strengths, ai_impact_detail, salary_range_low, salary_range_high, job_outlook) VALUES
-- CRITICAL RESISTANCE (< 15 risk)
('Cybersecurity Analyst', 'Technology', 8, 112000, 32, 'Zero-sum offense/defense game; AI cannot anticipate novel attack vectors', ARRAY['Threat Hunting', 'Incident Response', 'Security Architecture', 'Penetration Testing'], 95, 'Protects organizations from cyber threats through threat hunting, incident response, and security architecture design. High-stakes role where mistakes have real consequences.', 'Bachelor''s in CS/IT + Security certifications (CISSP, CEH)', 'Rapid growth as attacks evolve; 32% projected over 10 years', ARRAY['Continuous Learning', 'Problem Solving', 'Technical Depth', 'Ethical Mindset'], 'AI augments detection but cannot replace strategic security thinking', 85000, 145000, 'Excellent'),
('Registered Nurse', 'Healthcare', 5, 82600, 6, 'Hands-on patient care requires human touch, empathy, and real-time clinical judgment', ARRAY['Patient Assessment', 'Clinical Decision Making', 'Care Coordination', 'Health Education'], 98, 'Provides direct patient care, administers medications, and coordinates with healthcare teams. Emotional intelligence essential for patient support.', 'RN license (ASN/BSN), NCLEX-RN', 'Steady 6% growth; aging population drives demand', ARRAY['Empathy', 'Physical Stamina', 'Critical Thinking', 'Communication'], 'AI assistants help documentation but cannot replace bedside care', 65000, 110000, 'Excellent'),
('Mental Health Counselor', 'Healthcare', 3, 52400, 15, 'Deep emotional intelligence, therapeutic rapport, and ethical judgment cannot be replicated', ARRAY['Therapeutic Techniques', 'Crisis Intervention', 'Empathy', 'Ethical Reasoning'], 97, 'Helps clients navigate emotional and mental health challenges through talk therapy and interventions. Trust and rapport are foundational.', 'Master''s in Counseling/Psychology + State License', '15% growth; destigmatization increases demand', ARRAY['Empathy', 'Active Listening', 'Boundaries', 'Cultural Competence'], 'AI chatbots cannot replicate therapeutic alliance', 42000, 85000, 'Excellent'),
('Special Education Teacher', 'Education', 6, 64000, 4, 'Individualized accommodation, behavioral intervention, and parental liaison require human judgment', ARRAY['IEP Development', 'Behavioral Support', 'Parent Coaching', 'Adaptive Teaching'], 96, 'Teaches students with disabilities using individualized education plans. Requires constant adaptation to unique learning needs.', 'Bachelor''s in Special Ed + State Teaching License', 'Moderate growth; demand for inclusion specialists', ARRAY['Patience', 'Creativity', 'Advocacy', 'Collaboration'], 'AI cannot adapt to individual behavioral needs', 50000, 85000, 'Good'),
('Physical Therapist', 'Healthcare', 7, 97000, 17, 'Manual therapy, movement assessment, and patient motivation require physical embodiment', ARRAY['Manual Therapy', 'Movement Analysis', 'Rehabilitation', 'Patient Education'], 94, 'Helps patients recover movement and function through exercises and manual therapy. Hands-on care essential.', 'Doctor of Physical Therapy (DPT) + State License', 'Strong 17% growth; aging population', ARRAY['Manual Dexterity', 'Patience', 'Motivation', 'Technical Knowledge'], 'AI cannot perform manual interventions', 75000, 130000, 'Excellent'),
('Occupational Therapist', 'Healthcare', 9, 97000, 14, 'Adaptive techniques and daily living skills require personalized human support', ARRAY['ADL Training', 'Adaptive Equipment', 'Motor Skills', 'Work Rehabilitation'], 93, 'Helps patients regain daily living skills after injury or illness. Highly personalized approach required.', 'Master''s in OT + NBCOT certification', 'Strong 14% growth', ARRAY['Creativity', 'Patience', 'Problem Solving', 'Adaptability'], 'AI cannot adapt to individual needs in real-time', 70000, 125000, 'Excellent'),
('Dental Hygienist', 'Healthcare', 11, 82000, 10, ' Manual oral healthcare and patient comfort require human presence', ARRAY['Teeth Cleaning', 'Oral Health Education', 'Patient Comfort', 'Radiography'], 91, 'Provides dental cleanings and patient education. Patient comfort and trust are essential.', 'Associate''s in Dental Hygiene + State License', 'Steady 10% growth', ARRAY['Hand Skills', 'Communication', 'Patient Relations'], 'AI cannot replace human comfort element', 65000, 105000, 'Excellent'),
('Paramedic', 'Healthcare', 8, 48000, 11, 'Emergency medical response requires rapid decision-making under pressure', ARRAY['Emergency Care', 'Patient Stabilization', 'Ambulance Operations', 'CRIA Certification'], 93, 'Responds to emergencies, provides advanced life support, and transports patients. High-stakes decision making.', 'Paramedic certification + State License', '11% growth; demand for emergency services', ARRAY['Quick Thinking', 'Physical Stamina', 'Leadership', 'Technical Skills'], 'AI cannot make real-time emergency decisions', 35000, 65000, 'Good'),

-- VERY HIGH RESISTANCE (15-30 risk)
('AI Ethics Officer', 'Technology', 15, 145000, 45, 'Governance, bias auditing, and regulatory compliance require human accountability', ARRAY['AI Governance', 'Bias Auditing', 'Regulatory Compliance', 'Ethical Frameworks'], 90, 'Ensures AI systems are fair, transparent, and compliant. Serves as ethical gatekeeper for AI deployment.', 'Bachelor''s in CS/Phil/Policy + AI experience', 'Explosive 45% growth', ARRAY['Ethics', 'Policy Knowledge', 'Technical Understanding', 'Communication'], 'Human accountability cannot be delegated to AI', 120000, 180000, 'Excellent'),
('Social Worker', 'Healthcare', 18, 58000, 9, 'Case management, advocacy, and crisis intervention require deep human empathy', ARRAY['Case Management', 'Advocacy', 'Crisis Intervention', 'Resource Coordination'], 92, 'Connects clients with resources and supports them through crises. Emotional labor essential.', 'Bachelor''s/MSW + State License', 'Steady 9% growth', ARRAY['Empathy', 'Advocacy', 'Resourcefulness', 'Resilience'], 'AI cannot replicate emotional labor', 45000, 78000, 'Good'),
('Electrician', 'Trades', 12, 61000, 6, 'Installation, troubleshooting, and code compliance require physical presence', ARRAY['Electrical Installation', 'Troubleshooting', 'Code Compliance', 'Safety Protocols'], 93, 'Installs and repairs electrical systems. Physical work in variable environments.', 'Apprenticeship + State License', 'Steady 6% growth', ARRAY['Problem Solving', 'Physical Work', 'Safety Mindset'], 'AI cannot work on live systems', 45000, 85000, 'Good'),
('Plumber', 'Trades', 11, 64000, 5, 'Pipe fitting, diagnostic problem-solving in unpredictable environments requires manual dexterity', ARRAY['Pipe Fitting', 'Diagnostic Skills', 'Building Codes', 'Customer Relations'], 91, 'Installs and repairs plumbing systems. Problem-solving in tight spaces.', 'Apprenticeship + State License', 'Steady 5% growth', ARRAY['Problem Solving', 'Manual Dexterity', 'Customer Skills'], 'AI cannot access pipes physically', 48000, 90000, 'Good'),
('HVAC Technician', 'Trades', 14, 56000, 4, 'System installation, troubleshooting, and refrigerant handling require physical presence', ARRAY['System Installation', 'Refrigeration', 'Diagnostics', 'EPA Certification'], 90, 'Installs and maintains heating/cooling systems. Physical work with complex systems.', 'EPA 608 + HVAC certification', '4% growth; HVAC essential', ARRAY['Technical Skills', 'Physical Work', 'Problem Solving'], 'AI cannot handle refrigerants', 40000, 78000, 'Good'),
('Pilot', 'Transportation', 18, 160000, 5, 'Aircraft command, emergency response, and air traffic coordination require human decision-making', ARRAY['Flight Operations', 'Emergency Response', 'Navigation', 'Crew Management'], 95, 'Commands aircraft and ensures passenger safety. Ultimate responsibility rests with human.', 'Commercial Pilot License + ATP', '5% growth; essential role', ARRAY['Decision Making', 'Leadership', 'Pressure Handling'], 'AI assists but cannot be legally responsible', 120000, 250000, 'Good'),
('Air Traffic Controller', 'Transportation', 12, 138000, 3, 'Real-time coordination of aircraft requires split-second human judgment', ARRAY['Radar Monitoring', 'Communication', 'Conflict Resolution', 'Quick Decisions'], 94, 'Manages aircraft in airspace. Zero tolerance for error.', 'FAA Academy + Certification', '3% growth; critical role', ARRAY['Focus', 'Quick Thinking', 'Communication'], 'AI cannot match human throughput', 110000, 180000, 'Excellent'),
('Construction Project Manager', 'Construction', 25, 98000, 8, 'Complex stakeholder coordination, site safety decisions, and regulatory compliance require human oversight', ARRAY['Project Planning', 'Site Safety', 'Budget Management', 'Team Leadership'], 85, 'Oversees construction projects from start to finish. Multi-stakeholder management.', 'Bachelor''s in Construction/Project Management', '8% growth; infrastructure investment', ARRAY['Leadership', 'Problem Solving', 'Communication', 'Budgeting'], 'AI cannot physically oversee sites', 75000, 145000, 'Good'),
('Elevator Mechanic', 'Trades', 10, 88000, 4, 'Complex mechanical/electrical systems require hands-on problem-solving', ARRAY['Elevator Repair', 'Electrical Systems', 'Mechanical Systems', 'Safety Codes'], 92, 'Installs and repairs elevators. Specialized mechanical/electrical knowledge.', 'Apprenticeship + License', '4% growth; aging infrastructure', ARRAY['Mechanical Skills', 'Electrical Knowledge', 'Problem Solving'], 'AI cannot do hands-on repairs', 65000, 120000, 'Good'),
('Medical Laboratory Technologist', 'Healthcare', 20, 58000, 7, 'Lab analysis requires human judgment for ambiguous results', ARRAY['Lab Analysis', 'Quality Control', 'Microscopy', 'Specimen Processing'], 88, 'Performs medical tests to diagnose diseases. Critical thinking for abnormal results.', 'Bachelor''s in Medical Lab Science + ASCP', '7% growth; testing demand', ARRAY['Attention to Detail', 'Technical Skills', 'Problem Solving'], 'AI辅助 but cannot replace judgment', 45000, 78000, 'Good'),
('Healthcare Administrator', 'Healthcare', 22, 104000, 12, 'Complex regulatory navigation, stakeholder management, and strategic decisions require human judgment', ARRAY['Healthcare Regulation', 'Operations Management', 'Strategic Planning', 'Staff Leadership'], 88, 'Manages healthcare facilities. Regulatory expertise essential.', 'Master''s in Healthcare Administration', '12% growth', ARRAY['Leadership', 'Regulatory Knowledge', 'Strategic Thinking'], 'AI cannot navigate human regulations', 80000, 155000, 'Good'),

-- HIGH RESISTANCE (30-50 risk)
('Attorney', 'Legal', 28, 145000, 4, 'Courtroom advocacy, strategy development, and client trust require human judgment and accountability', ARRAY['Legal Strategy', 'Litigation', 'Client Counseling', 'Negotiation'], 88, 'Represents clients in legal matters. Advocacy requires human presence.', 'JD + State Bar', '4% growth; essential function', ARRAY['Argumentation', 'Research', 'Client Relations', 'Ethics'], 'AI cannot replace courtroom presence', 110000, 250000, 'Good'),
('HR Business Partner', 'People Ops', 32, 85000, 8, 'Employee relations, conflict resolution, and cultural development require human emotional intelligence', ARRAY['Employee Relations', 'Conflict Resolution', 'Org Development', 'Coaching'], 85, 'Strategic HR partner. Employee relations require human touch.', 'Bachelor''s in HR + SHRM-CP', '8% growth', ARRAY['Emotional Intelligence', 'Communication', 'Problem Solving'], 'AI cannot resolve conflicts', 65000, 130000, 'Good'),
('Financial Advisor', 'Finance', 35, 95000, 7, 'Holistic wealth planning, behavioral coaching, and regulatory compliance require fiduciary trust', ARRAY['Wealth Planning', 'Risk Assessment', 'Client Relationships', 'Regulatory Knowledge'], 82, 'Provides financial advice. Trust and relationship essential.', 'CFP certification + Series 65', '7% growth', ARRAY['Trust Building', 'Technical Knowledge', 'Communication'], 'AI cannot replace fiduciary relationship', 70000, 150000, 'Good'),
('Data Scientist', 'Technology', 45, 130000, 36, 'Model interpretation, business insight translation, and strategic recommendation require human context', ARRAY['Statistical Analysis', 'ML Modeling', 'Business Intelligence', 'Data Storytelling'], 75, 'Extracts insights from data. Business context essential.', 'Bachelor''s in Stats/CS + Python/R', '36% growth', ARRAY['Business Acumen', 'Technical Depth', 'Communication'], 'AI assists but cannot interpret business context', 95000, 200000, 'Good'),
('Product Manager', 'Technology', 42, 140000, 20, 'Strategic roadmap, stakeholder negotiation, and UX intuition require human synthesis', ARRAY['Product Strategy', 'User Research', 'Stakeholder Management', 'Roadmap Planning'], 78, 'Leads product strategy. Stakeholder management essential.', 'Bachelor''s + Product experience', '20% growth', ARRAY['Strategic Thinking', 'User Empathy', 'Leadership'], 'AI cannot replace human intuition', 110000, 200000, 'Good'),
('UX Researcher', 'Technology', 40, 105000, 25, 'Qualitative insights, ethnographic research, and stakeholder empathy require human connection', ARRAY['User Interviews', 'Usability Testing', 'Journey Mapping', 'Research Synthesis'], 83, 'Researches user needs. Human connection essential.', 'Bachelor''s in HCI/Psych + Research methods', '25% growth', ARRAY['Empathy', 'Qualitative Skills', 'Communication'], 'AI cannot replicate human connection', 80000, 155000, 'Good'),
('Marketing Director', 'Marketing', 38, 135000, 10, 'Brand strategy, creative direction, and stakeholder relationships require human intuition', ARRAY['Brand Strategy', 'Creative Leadership', 'Campaign Optimization', 'Team Management'], 80, 'Leads marketing strategy. Creative direction essential.', 'Bachelor''s in Marketing + MBA preferred', '10% growth', ARRAY['Creativity', 'Leadership', 'Strategic Thinking'], 'AI cannot lead creatively', 100000, 220000, 'Good'),
('Cloud Solutions Architect', 'Technology', 42, 155000, 25, 'Complex system design, cost optimization, and multi-cloud strategy require architectural judgment', ARRAY['System Architecture', 'Cloud Strategy', 'Cost Optimization', 'Security Design'], 80, 'Designs cloud solutions. Strategic architecture.', 'Bachelor''s + AWS/Azure/GCP certs', '25% growth', ARRAY['Technical Depth', 'Strategic Thinking', 'Cost Awareness'], 'AI cannot design architectures', 120000, 220000, 'Good'),
('Machine Learning Operations Engineer', 'Technology', 48, 145000, 45, 'ML pipeline orchestration, model monitoring, and infrastructure require operational expertise', ARRAY['MLOps', 'Pipeline Orchestration', 'Model Monitoring', 'Cloud Infrastructure'], 76, 'Operates ML systems at scale. Operational excellence required.', 'Bachelor''s + MLOps experience', '45% growth', ARRAY['Operations', 'Infrastructure', 'Automation'], 'AI cannot operate itself', 110000, 200000, 'Good'),
('Sales Director', 'Sales', 48, 145000, 12, 'Complex negotiation, relationship building, and strategic account management require human persuasion', ARRAY['Strategic Selling', 'Negotiation', 'Account Management', 'Team Leadership'], 72, 'Leads sales strategy. Relationship building essential.', 'Bachelor''s + Sales experience', '12% growth', ARRAY['Relationship Building', 'Negotiation', 'Leadership'], 'AI cannot build relationships', 110000, 280000, 'Good'),

-- EMERGING/TRANSITIONAL ROLES (50-65 risk)
('Prompt Engineer', 'Technology', 55, 125000, 80, 'LLM optimization and AI tooling requires human creativity; future uncertain but currently high demand', ARRAY['Prompt Design', 'LLM Optimization', 'AI Tooling', 'Evaluation Metrics'], 70, 'Optimizes LLM prompts. New role with high demand.', 'Technical background + AI familiarity', '80% growth; emerging role', ARRAY['Creativity', 'Technical Learning', 'Experimentation'], 'Currently valuable, long-term uncertain', 95000, 180000, 'Uncertain'),
('AI Training Data Specialist', 'Technology', 52, 95000, 60, 'Data curation, quality assurance, and annotation require human judgment on labeling accuracy', ARRAY['Data Labeling', 'Quality Assurance', 'Annotation Guidelines', 'Model Evaluation'], 72, 'Labels and curates training data. Quality essential.', 'Attention to detail + Domain knowledge', '60% growth', ARRAY['Attention to Detail', 'Consistency', 'Domain Knowledge'], 'Essential for AI training', 70000, 135000, 'Moderate'),
('Robotics Technician', 'Trades', 45, 68000, 15, 'Robot installation, programming, and maintenance require hands-on expertise', ARRAY['Robot Programming', 'Preventive Maintenance', 'Troubleshooting', 'Safety Protocols'], 78, 'Installs and maintains robots. Hands-on essential.', 'Associates in Robotics + Manufacturer training', '15% growth', ARRAY['Mechanical Skills', 'Programming', 'Problem Solving'], 'AI cannot maintain itself', 50000, 95000, 'Good'),
('Wind Turbine Technician', 'Trades', 38, 58000, 9, 'On-site turbine maintenance requires physical presence and troubleshooting', ARRAY['Turbine Repair', 'Electrical Systems', 'Climbing', 'Safety Protocols'], 82, 'Maintains wind turbines. Physical work at heights.', 'Wind turbine certification + OSHA 10', '9% growth; renewable energy', ARRAY['Physical Work', 'Safety Mindset', 'Technical Skills'], 'AI cannot perform physical repairs', 45000, 85000, 'Good'),
('Solar Photovoltaic Installer', 'Trades', 40, 52000, 27, 'On-site solar installation requires physical presence and electrical knowledge', ARRAY['Solar Installation', 'Electrical Wiring', 'Roof Work', 'Code Compliance'], 80, 'Installs solar panels. Growing renewable energy sector.', 'Solar installation certification + Electrical knowledge', '27% growth', ARRAY['Physical Work', 'Electrical Knowledge', 'Safety'], 'AI cannot do physical installation', 40000, 78000, 'Good'),
('Family Medicine Physician', 'Healthcare', 15, 225000, 5, 'Comprehensive patient care requires long-term relationships and holistic judgment', ARRAY['Primary Care', 'Diagnosis', 'Patient Relationships', 'Preventive Care'], 92, 'Provides comprehensive healthcare. Relationship-based care.', 'MD/DO + Family Medicine Residency', '5% growth; essential care', ARRAY['Patient Relationships', 'Diagnostic Skills', 'Holistic Thinking'], 'AI cannot replace holistic judgment', 175000, 295000, 'Excellent'),
('Pediatrician', 'Healthcare', 12, 190000, 4, 'Child healthcare requires specialized communication and developmental knowledge', ARRAY['Pediatric Care', 'Developmental Assessment', 'Parent Communication', 'Vaccination'], 93, 'Cares for children. Communication skills essential.', 'MD/DO + Pediatric Residency', '4% growth', ARRAY['Child Communication', 'Developmental Knowledge', 'Patience'], 'AI cannot communicate with children', 150000, 280000, 'Excellent'),
('Surgeon', 'Healthcare', 10, 265000, 3, 'Surgical procedures require real-time judgment and manual dexterity', ARRAY['Surgical Procedures', 'Anatomy', 'Emergency Response', 'Team Leadership'], 95, 'Performs surgeries. Ultimate manual/mental skill.', 'MD/DO + Surgical Residency', '3% growth', ARRAY['Manual Dexterity', 'Focus', 'Decision Making', 'Team Leadership'], 'AI assists but cannot operate', 200000, 450000, 'Excellent'),
('Dentist', 'Healthcare', 18, 175000, 7, 'Oral healthcare requires manual precision and patient relationships', ARRAY['Dental Procedures', 'Diagnosis', 'Patient Education', 'Surgery'], 90, 'Provides oral healthcare. Manual skill essential.', 'DDS/DMD + State License', '7% growth', ARRAY['Manual Dexterity', 'Patient Relations', 'Diagnostic Skills'], 'AI cannot perform procedures', 135000, 295000, 'Excellent'),
('Pharmacist', 'Healthcare', 25, 132000, 4, 'Medication counseling and drug interaction checking require professional judgment', ARRAY['Medication Management', 'Patient Counseling', 'Drug Interactions', 'Regulatory Compliance'], 87, 'Dispenses medications and advises patients. Safety-critical role.', 'PharmD + State License', '4% growth', ARRAY['Attention to Detail', 'Communication', 'Safety Mindset'], 'AI assists but cannot replace judgment', 105000, 165000, 'Good'),
('Veterinarian', 'Healthcare', 20, 115000, 17, 'Animal care requires diagnostic skills and patient (animal) communication', ARRAY['Animal Diagnosis', 'Surgery', 'Patient Communication', 'Treatment Planning'], 88, 'Provides animal healthcare. Diagnostic skills essential.', 'DVM + State License', '17% growth', ARRAY['Animal Communication', 'Diagnostic Skills', 'Surgery'], 'AI cannot diagnose animals', 90000, 185000, 'Good'),
('Psychologist', 'Healthcare', 15, 85000, 14, 'Clinical assessment and therapy require human connection and expertise', ARRAY['Psychological Assessment', 'Therapy', 'Diagnosis', 'Research'], 90, 'Provides mental health services. Deep expertise required.', 'PhD/PsyD + State License', '14% growth', ARRAY['Empathy', 'Research', 'Clinical Skills'], 'AI cannot replace clinical expertise', 65000, 145000, 'Excellent'),
('Physical Therapy Assistant', 'Healthcare', 18, 62000, 25, 'Assists PTs with rehabilitation; direct patient interaction', ARRAY['Therapeutic Exercises', 'Patient Motivation', 'Equipment Operation', 'Documentation'], 86, 'Assists physical therapists. Patient interaction essential.', 'Associate''s in PTA + License', '25% growth', ARRAY['Patient Interaction', 'Physical Work', 'Motivation'], 'AI cannot do hands-on assistance', 48000, 85000, 'Good'),
('Speech-Language Pathologist', 'Healthcare', 12, 87000, 21, 'Speech therapy requires human interaction and personalized techniques', ARRAY['Speech Therapy', 'Swallowing Assessment', 'Patient Communication', 'Treatment Planning'], 89, 'Treats speech and swallowing disorders. Personal care essential.', 'Master''s in SLP + CCC-SLP', '21% growth', ARRAY['Patient Interaction', 'Technical Skills', 'Creativity'], 'AI cannot replicate personal therapy', 70000, 125000, 'Excellent'),
('Optometrist', 'Healthcare', 20, 125000, 6, 'Eye exams and vision care require professional judgment', ARRAY['Eye Exams', 'Diagnosis', 'Prescription', 'Patient Education'], 88, 'Provides eye care. Diagnostic skills essential.', 'OD + State License', '6% growth', ARRAY['Diagnostic Skills', 'Patient Relations', 'Technology'], 'AI cannot replace professional judgment', 100000, 185000, 'Good')
ON CONFLICT (role_title, industry_label) DO NOTHING;